# Generated by Django 6.0.7 on 2026-07-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Malik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daire_no', models.CharField(max_length=20, unique=True)),
                ('ad_soyad', models.CharField(max_length=200)),
                ('muaf_mi', models.BooleanField(default=False)),
                ('aktif_mi', models.BooleanField(default=True)),
                ('temmuz_oncesi_durum', models.CharField(choices=[('TAMAM', 'Tamam'), ('EKSIK', 'Eksik'), ('MUAF', 'Muaf')], default='TAMAM', max_length=20)),
                ('notlar', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
