# Generated by Django 6.0.7 on 2026-07-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AidatDonemi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donem_adi', models.CharField(max_length=100)),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('aktif_mi', models.BooleanField(default=True)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Aidat Dönemi',
                'verbose_name_plural': 'Aidat Dönemleri',
            },
        ),
        migrations.AlterModelOptions(
            name='malik',
            options={'verbose_name': 'Malik', 'verbose_name_plural': 'Malikler'},
        ),
    ]
