# Generated by Django 6.0.7 on 2026-07-20 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aidatdonemi_alter_malik_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MalikOdemesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField()),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('odeme_tipi', models.CharField(choices=[('N', 'Nakit'), ('D', 'Çek/Kart')], max_length=1)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aidatdonemi')),
                ('malik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odemeler', to='core.malik')),
            ],
            options={
                'verbose_name': 'Malik Ödemesi',
                'verbose_name_plural': 'Malik Ödemeleri',
            },
        ),
    ]
