# Generated by Django 6.0.7 on 2026-07-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_malikodemesi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malikodemesi',
            name='tarih',
            field=models.DateField(blank=True, null=True),
        ),
    ]
