# Generated by Django 6.0.7 on 2026-07-21 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_malikodemesi_tarih'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiderKategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, unique=True)),
                ('aktif_mi', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Gider Kategorisi',
                'verbose_name_plural': 'Gider Kategorileri',
            },
        ),
        migrations.CreateModel(
            name='Gider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('odeme_tipi', models.CharField(choices=[('N', 'Nakit'), ('D', 'Çek/Kart')], max_length=1)),
                ('aciklama', models.CharField(max_length=500)),
                ('tarih', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.giderkategori')),
            ],
            options={
                'verbose_name': 'Gider',
                'verbose_name_plural': 'Giderler',
            },
        ),
    ]
