# Generated by Django 6.0.7 on 2026-07-21 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_giderkategori_gider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gider',
            name='kategori',
        ),
    ]
