# Generated by Django 6.0.7 on 2026-07-21 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_gider_kategori'),
    ]

    operations = [
        migrations.CreateModel(
            name='MalikAidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('aciklama', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ozel_aidatlar', to='core.aidatdonemi')),
                ('malik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ozel_aidatlar', to='core.malik')),
            ],
            options={
                'verbose_name': 'Özel Aidat Tutarı',
                'verbose_name_plural': 'Özel Aidat Tutarları',
                'unique_together': {('malik', 'donem')},
            },
        ),
    ]
