# Generated by Django 6.0.7 on 2026-07-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_malikaidat'),
    ]

    operations = [
        migrations.CreateModel(
            name='FonHareketi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField()),
                ('hareket_tipi', models.CharField(choices=[('GELIR', 'Gelir'), ('GIDER', 'Gider')], max_length=10)),
                ('aciklama', models.CharField(max_length=500)),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fon Hareketi',
                'verbose_name_plural': 'Fon Hareketleri',
            },
        ),
    ]
