# Generated by Django 6.0.7 on 2026-07-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_fonhareketi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hakedis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField()),
                ('aciklama', models.CharField(max_length=300)),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hakediş',
                'verbose_name_plural': 'Hakedişler',
            },
        ),
    ]
