# Generated by Django 6.0.7 on 2026-07-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_hakedis'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevletHakedisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField()),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Devlet Hakedişi',
                'verbose_name_plural': 'Devlet Hakedişleri',
            },
        ),
        migrations.AlterField(
            model_name='fonhareketi',
            name='hareket_tipi',
            field=models.CharField(choices=[('GELIR', 'Gelir'), ('GIDER', 'Gider'), ('HAKEDIS', 'Hakediş')], max_length=10),
        ),
    ]
