# Generated by Django 6.0.7 on 2026-08-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_devlethakedisi_delete_hakedis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borclu_adi', models.CharField(max_length=200)),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Borç',
                'verbose_name_plural': 'Borçlar',
            },
        ),
        
    ]
