# Generated by Django 6.0.7 on 2026-08-01 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_borc_delete_hakedis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hakedis',
        ),
    ]
